name: Twisted Skies
favicon: null
layout_spectrum: 0.24394
typography_spectrum: 0.05809
title: Twisted Skies Chase Team
description: 'Chasing, Forecasting, and Providing Ground Truth'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C0C8'
    - '#184828'
    - '#707078'
    - '#40BF6A'
    - '#000000'
  brandStrength: 1
  lightness: 0
  saturation: 0.183002
  rhythmicContrast: 1
purpose: []
