typography_spectrum: 0.33899
color:
  brandColors:
    - '#C0C0C8'
    - '#184828'
    - '#707078'
    - '#40BF6A'
    - '#000000'
  brandStrength: 1
  lightness: 0
  saturation: 0.183002
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24244
analytics:
  google: null
  facebook: null
  twitter: null
name: Twisted Skies
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Twisted Skies Chase Team
description: 'Chasing, Forecasting, and Providing Ground Truth'
purpose: []
