analytics: {}
color:
  brandColors:
    - '#C0C0C8'
    - '#184828'
    - '#707078'
    - '#40BF6A'
    - '#000000'
  brandStrength: 0.671875
  lightness: 0.071886
  rhythmicContrast: 0.485573
  saturation: 0.183002
cta: {}
layout_spectrum: 0.504934
name: Twisted Skies
opengraph: {}
purpose: []
typography_spectrum: 0.33899
